[2023-09-20 11:45:15,814] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: my_first_dag_v2.second_task 2023-09-20T07:00:00+00:00 [queued]>
[2023-09-20 11:45:15,955] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: my_first_dag_v2.second_task 2023-09-20T07:00:00+00:00 [queued]>
[2023-09-20 11:45:15,956] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-09-20 11:45:15,956] {taskinstance.py:1069} INFO - Starting attempt 1 of 6
[2023-09-20 11:45:15,956] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-09-20 11:45:16,006] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): second_task> on 2023-09-20T07:00:00+00:00
[2023-09-20 11:45:16,029] {standard_task_runner.py:52} INFO - Started process 1751 to run task
[2023-09-20 11:45:16,052] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag_v2', 'second_task', '2023-09-20T07:00:00+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpe7gczaly', '--error-file', '/tmp/tmp0t3oclk3']
[2023-09-20 11:45:16,077] {standard_task_runner.py:77} INFO - Job 11: Subtask second_task
[2023-09-20 11:45:16,432] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag_v2.second_task 2023-09-20T07:00:00+00:00 [running]> on host cf5d18783b85
[2023-09-20 11:45:16,683] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rhythmbear
AIRFLOW_CTX_DAG_ID=my_first_dag_v2
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-20T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-20T07:00:00+00:00
[2023-09-20 11:45:16,684] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-09-20 11:45:16,686] {bash.py:158} INFO - Running command: echo I am the 2nd task, I run after the first
[2023-09-20 11:45:16,718] {bash.py:169} INFO - Output:
[2023-09-20 11:45:16,724] {bash.py:173} INFO - I am the 2nd task, I run after the first
[2023-09-20 11:45:16,726] {bash.py:177} INFO - Command exited with return code 0
[2023-09-20 11:45:16,922] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v2, task_id=second_task, execution_date=20230920T070000, start_date=20230920T114515, end_date=20230920T114516
[2023-09-20 11:45:17,156] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-20 11:45:17,217] {local_task_job.py:146} INFO - Task exited with return code 0
